### ISSUE TITLE
Unable to install diffefwi

### ISSUE THREAD

**Issue by shwetageoradar** [DeepWave-KAUST/diffefwi#1]
I am trying to install the diffefwi to macmini2 but  I am unable to do it. It's showing error of PackagesNotFoundError. To me it seems to arise from building dependencies. Please can someone help. I have tried changing the install.sh file but could not resolve the issue.

**Comment by hatsyim** [comment]
Hi, 

To clarify, the system you are attempting to install our package into is an ARM-based Mac, right?

If that is the case, we believe substantial changes need to be made to accommodate non-NVIDIA GPUs at the moment, not to mention that you might not be able to perform your diffusion model with your GPU.

However, we provide an additional notebook that can be run directly from existing open-source GPU providers like Google Colab. Note that we only select the T4 GPU as an example, stronger GPU might be needed to train your own diffusion model.

You can find the details under https://github.com/DeepWave-KAUST/diffefwi/blob/main/notebooks/colab.ipynb

**Comment by shwetageoradar** [comment]
Yes it is ARM-based Mac. Thank you for guiding me.
